name: Deploy Spring Boot ECS

on:
  push:
    branches:
      - main


permissions:
  id-token: write
  contents: read


env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: springboot-ecs-repo
  ECS_CLUSTER: springboot-ecs-cluster
  ECS_SERVICE: springboot-ecs-service
  CONTAINER_NAME: springboot-container


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::937749309122:role/github-actions-ecs-role
        aws-region: ${{ env.AWS_REGION }}


    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build and push Docker image
      id: build-image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          937749309122.dkr.ecr.ap-south-1.amazonaws.com/springboot-ecs-repo:${{ github.sha }}


    - name: Download current ECS task definition
      run: |

        aws ecs describe-task-definition \
        --task-definition springboot-ecs-task \
        --query taskDefinition \
        > task-definition.json


    - name: Render ECS task definition
      id: render-task
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: springboot-container
        image: 937749309122.dkr.ecr.ap-south-1.amazonaws.com/springboot-ecs-repo:${{ github.sha }}


    - name: Deploy ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-task.outputs.task-definition }}
        service: springboot-ecs-service
        cluster: springboot-ecs-cluster
        wait-for-service-stability: true
